import React from "react";
import Link from "next/link"
import Head from "next/head";

const Homepage = () => {
	return (
        <div>
            <Head>
				<title>Farmly Kenya</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

            <main>
                <h1>Homepage</h1>
            <Link href="./ap/services">Services</Link>
            <Link href="./nu/register" passHref >
                <button>
                    Register
                </button>
            </Link>
            <Link href="./ap/login" passHref >
                <button>
                    Login
                </button>
            </Link>
            </main>
            
        </div>
    ) 
    
};

export default Homepage;
